services:
  jellyfin:
    # https://github.com/jellyfin/jellyfin
    image: ghcr.io/jellyfin/jellyfin:12
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - media-tier
    ports:
      - 8096:8096
    volumes:
      - ${JELLYFIN_APPDATA_PATH:?}/config:/config
      - ${JELLYFIN_APPDATA_PATH:?}/cache:/cache
      - ${MEDIA_PATH:?}:/srv/media
    environment:
      - TZ=Europe/Berlin
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_DOMAIN:?}

networks:
  media-tier:
    external: true
