services:
  web:
    # https://github.com/calagopus/panel
    image: ghcr.io/calagopus/panel:heavy
    container_name: calagopus-panel
    restart: unless-stopped
    stop_grace_period: 40s
    depends_on:
      - db
      - cache
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    networks:
      - pangolin
      - default
    volumes:
      - ${CALAGOPUS_PANEL_APPDATA_PATH:?}/data:/var/lib/calagopus
      - ${CALAGOPUS_PANEL_APPDATA_PATH:?}/logs:/var/log/calagopus
      - ${CALAGOPUS_PANEL_APPDATA_PATH:?}/build/binaries:/app/binaries
      - ${CALAGOPUS_PANEL_APPDATA_PATH:?}/build/translations:/app/translations
      - ${CALAGOPUS_PANEL_APPDATA_PATH:?}/build/extensions:/app/extensions
      - ${CALAGOPUS_PANEL_APPDATA_PATH:?}/build/extension-migrations:/app/repo/database/extension-migrations
    environment:
      - TZ=Europe/Berlin
      - REDIS_URL=redis://cache
      - DATABASE_URL=postgresql://panel:${POSTGRES_PASSWORD:?}@db/panel
      - DATABASE_MIGRATE=true
      - PORT=8000
      - APP_DEBUG=false
      - APP_LOG_DIRECTORY=/var/log/calagopus
      - APP_PRIMARY=true
      - APP_ENABLE_WINGS_PROXY=true
      - APP_ENCRYPTION_KEY=${APP_ENCRYPTION_KEY:?}
      - APP_USE_DECRYPTION_CACHE=true
      - APP_USE_INTERNAL_CACHE=true
      - APP_DISABLE_EXTENSION_MANAGEMENT=false
      - APP_TRUSTED_PROXIES=${APP_TRUSTED_PROXIES:?}

  db:
    image: ghcr.io/calagopus/pgautoupgrade:18-alpine
    container_name: calagopus-db
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=panel
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=panel
      - PGDATA=/data
    volumes:
      - ${CALAGOPUS_PANEL_APPDATA_PATH:?}/postgres:/data

  cache:
    image: ghcr.io/calagopus/valkey:latest
    container_name: calagopus-redis
    restart: unless-stopped
    command: --protected-mode no --save 60 1
    environment:
      TZ: Europe/Berlin
    volumes:
      - ${CALAGOPUS_PANEL_APPDATA_PATH:?}/cache:/data

networks:
  pangolin:
    external: true