services:
  mediathekarr:
    # https://github.com/PCJones/MediathekArr
    image: pcjones/mediathekarr:latest
    container_name: mediathekarr
    restart: unless-stopped
    networks:
      - media-tier
    volumes:
      - ${DOWNLOADS_PATH:?}/incomplete:/app/downloads
    environment:
      - TZ=Europe/Berlin
      - DOWNLOAD_FOLDER_PATH_MAPPING=${DOWNLOADS_PATH:?}/complete

networks:
  media-tier:
    external: true