services:
  outline:
    # https://github.com/outline/outline
    image: outlinewiki/outline:1.10
    container_name: outline_server-dnd
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - outline-dnd
      - pangolin
    volumes:
      - ${OUTLINE_DND_APPDATA_PATH:?}/config:/var/lib/outline/data
    environment:
      - URL=${OUTLINE_DND_URL:?}
      - SECRET_KEY=${SECRET_KEY:?}
      - UTILS_SECRET=${UTILS_SECRET:?}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD:?}@postgres:5432/outline
      - PGSSLMODE=disable
      - REDIS_URL=redis://redis:6379
      - FILE_STORAGE=local
      - FILE_STORAGE_UPLOAD_MAX_SIZE=262144000
      - FORCE_HTTPS=false
      - RATE_LIMITER_ENABLED=true
      # OIDC
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:?}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET:?}
      - OIDC_AUTH_URI=${OIDC_AUTH_URL:?}
      - OIDC_TOKEN_URI=${OIDC_TOKEN_URL:?}
      - OIDC_USERINFO_URI=${OIDC_USERINFO_URL:?}
      - OIDC_LOGOUT_URI=${OIDC_LOGOUT_URL:?}
      - OIDC_DISPLAY_NAME=${OIDC_DISPLAY_NAME:?}
      # SMTP
      - SMTP_HOST=${SMTP_HOST:?}
      - SMTP_PORT=465
      - SMTP_USERNAME=${SMTP_USERNAME:?}
      - SMTP_PASSWORD=${SMTP_PASSWORD:?}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:?}
      - SMTP_NAME=${SMTP_NAME:?}

  postgres:
    image: postgres:16-alpine
    container_name: outline_postgres-dnd
    restart: unless-stopped
    networks:
      - outline-dnd
    volumes:
      - ${OUTLINE_DND_APPDATA_PATH:?}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=outline
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=outline
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "outline"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: outline_redis-dnd
    restart: unless-stopped
    command: ["redis-server", "/redis.conf"]
    networks:
      - outline-dnd
    volumes:
      - ${OUTLINE_DND_APPDATA_PATH:?}/redis.conf:/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

networks:
  outline-dnd:
    external: true
  pangolin:
    external: true
