services:
  paperless-webserver:
    # https://github.com/paperless-ngx/paperless-ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:3.3
    container_name: paperless-webserver
    restart: unless-stopped
    depends_on:
      - paperless-broker
      - paperless-gotenberg
      - paperless-tika
    ports:
      - 8000:8000
    volumes:
      - ${PAPERLESS_DATA_PATH:?}/data:/usr/src/paperless/data
      - ${PAPERLESS_MEDIA_PATH:?}/media:/usr/src/paperless/media
      - ${PAPERLESS_MEDIA_PATH:?}/export:/usr/src/paperless/export
      - ${PAPERLESS_MEDIA_PATH:?}/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBENGINE: sqlite
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY:?}
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://${PAPERLESS_DOMAIN:?}
      PAPERLESS_ALLOWED_HOSTS: ${PAPERLESS_ALLOWED_HOSTS:?}
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIME_ZONE: Europe/Berlin
      #PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      #PAPERLESS_SOCIALACCOUNT_PROVIDERS: ${PAPERLESS_SOCIALACCOUNT_PROVIDERS:?}
  
  paperless-broker:
    # https://hub.docker.com/r/valkey/valkey
    image: valkey/valkey:9-alpine
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - ${PAPERLESS_DATA_PATH:?}/valkey:/data
  
  paperless-gotenberg:
    # https://hub.docker.com/r/gotenberg/gotenberg
    image: gotenberg/gotenberg:8
    container_name: paperless-gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  paperless-tika:
    # https://hub.docker.com/r/apache/tika
    image: apache/tika:3.3.1.0
    container_name: paperless-tika
    restart: unless-stopped